/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nikki Sonali' at '9/4/17 2:37 PM' with Gradle 2.14.1
 *
 * @author Nikki Sonali, @date 9/4/17 2:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
